### PR TITLE
Fix typo in help message

### PR DESCRIPTION
**Pull request by NateEag**
I noticed this while tinkering with my install of the tool.

It's a quick guess at the correct fix done in the web editor - I think it's plausible but I haven't actually tested it.

### CODE REVIEW

**Comment by languitar** [comment]
Thanks for the fix! The commit message needs to follow a certain convention in this project. Can you reword it or should I fix it myself?

```
docs: fix typo in help message
```

Would work

**Comment by NateEag** [comment]
Yup, I should be able to do that in a bit here.

**Comment by NateEag** [comment]
Okay, I've done a force-push that rewords the commit message.

Doesn't seem to have updated the CI results. 🤷

Is there something I can do to retrigger CI?

**Comment by languitar** [comment]
Thanks for the patience! That works now.

**Comment by NateEag** [comment]
You're very welcome. Thanks for the merge!

**Pull request merged**
