### PR TITLE
consider protocol for github API tokens

### PR DESCRIPTION
**Pull request by rpuntaie**
See the explanation in the README.

### CODE REVIEW

**Comment by languitar** [comment]
Thanks for the PR. I don't understand the motivation for this. Despite deprecating plain password authentication, tokens are simply a replacement for the password when operating with https, right? Why is special logic required here?

**Comment by rpuntaie** [comment]
There is no special logic required.
But tokens are HTTPS specific.

The user might have a password for github in its `pass` store.
I have.

Now I would like to store the token there, too, without removing or replacing my github password.
The protocol provided by `git` allows to make a distinction.

The pull request allows the user to use the protocol.
The protocol was not available so far.

This change was done keeping full backward compatibility,
but allowing `[https://...]` header for https tokens,
kind of like a marker for tokens.

**Comment by languitar** [comment]
But the usual Github password so far used to work for the same protocol. So how does having the protocol (which is always the same, SSH is not support) available for matching help?

I personally would use something like the passwordstore layout:
```
dev/github.com/user
dev/github.com/token
```

And a respective config entry would then be
```ini
[github.com*]
target=dev/github.com/token
```

**Comment by rpuntaie** [comment]
I use the [browserpass web extension](https://github.com/browserpass/browserpass-extension). The tokens don't need to figure there. So I wanted them with a more private naming. I chose `https_github.com`, but it could have been `token_github.com`.
And I didn't want to change the layout of my other passwords.

But you are right: I can map to

```INI
[github.com*]
target=https_github.com/token
```

`git-pass-mapping.ini` is only for `pass-helper-git` anyway. 
The naming in `pass` is completely independent from the headers in `git-pass-mapping.ini`.

I close this and will remove my clone. Sorry for the noise.

**Comment by languitar** [comment]
Good that this solution works for you. Is there any documentation missing to avoid such an issue in the future?

**Comment by rpuntaie** [comment]
Maybe some general introduction to the context at the beginning? I will make a suggestion via another pull request.

**Pull request closed without merging**
