### PR TITLE
Added support for storing password and username that are returned by git back into pass

### PR DESCRIPTION
**Pull request by Xgames123**
Issue: #277 

Current Inserters: template, null
template: uses a template (login: ${username})
null: always outputs an empty string (used for if you don't want to store the username)

### CODE REVIEW

**Comment by languitar** [comment]
Thank you for providing this feature! Can you extend the tests to include the store operation of the main program and add documentation for this to make the new feature understandable for users? I can assist in case you need help.

**Comment by Xgames123** [comment]
Why Is it complaining now?
Everything is covered except for branches to handle critical errors.
https://app.codecov.io/gh/languitar/pass-git-helper/pull/280

**Comment by Xgames123** [comment]
After writing the docs I noticed that the configuration is now kind of a mess.
Maybe we could have some sort of mini template engine thing for like an entire section (inserting/extracting)
```ini
[github.com]
target="dev/test"
template={ # this is invalid ini syntax but it isn't that hard to write a custom ini parser
${0}password: "${password}" # ${n} will lock that to a specific line in the config
usrname: "${username}"
}
```
But this will require a rewrite of basically everything and it breaks backwards compatibility.

**Comment by languitar** [comment]
> Why Is it complaining now? Everything is covered except for branches to handle critical errors.

The coverage of the changed lines in this PR is below the full coverage of the project. This effectively means that after merging coverage will be lower. But that's ok if some paths are not worth covering with tests.

**Comment by languitar** [comment]
> After writing the docs I noticed that the configuration is now kind of a mess. Maybe we could have some sort of mini template engine thing for like an entire section (inserting/extracting)

...

> But this will require a rewrite of basically everything and it breaks backwards compatibility.

I wouldn't want to maintain a custom parser for this. However, the Python configparser module used here already supports multiline values: https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

> Values can also span multiple lines, as long as they are indented deeper than the first line of the value.

Isn't that enough to come up with something like:

```ini
[DEFAULT]
insertion_target=dev/${host}/${username}
insertion_template=${password}
    username: ${username}
```

Then the implementation can probably also be simplified by removing insertion strategies completely?

**Comment by Xgames123** [comment]
> 

But then it still requires that you configure everything twice for extraction and insertion
```ini
[DEFAULT]
target=dev/${host}/${username}
username_extractor=regex_search
regex_username=^username: (.*)$
insertion_template=${password}
    username: ${username}
```
I was thinking like removing the extraction and just having a single syntax that can both insert and extract.

and also the targets can be specified in command line arguments and have something like this in .gitconfig
```ini
[credential "https://github.com/Xgames123"] # this will match all repos of user xgames123
  helper = '/usr/bin/pass-git-helper' -m {host} -t dev/{host}/{username} # no $ because it needs to be escaped for shell
```
You could also make a symlink to git-credential-pass to just use pass instead of the full path
```ini
[credential "https://github.com/Xgames123"] # this will match all repos of user xgames123
  helper = pass -m {host} -t dev/{host}/{username}
```
.config/pass-git-helper/github.com
```
^{0}password: ${password}
username: ${username}
```

Its probably  not a good idea to remake the entire config system because it will break backwards compatibility. So we probably need another solution.

**Comment by languitar** [comment]
Having different config fragments for reading and inserting sounds fine to me. Let's not over-engineer this for the moment. This is a more or less simple script and storing hasn't been requested before. Maybe a simple solution works for the moment?

**Comment by Xgames123** [comment]
https://github.com/Xgames123/git-credential-pass

**Pull request closed without merging**
