### PR TITLE
Add `file_is_username` option

### PR DESCRIPTION
**Pull request by DIzFer**
Another of the possible layouts for the passwordstore is to have a domain/username structure, with the content being only the password. This makes it easier to handle, for example, expiring passwords, where I have to `pass generate` every 30 days, overwriting the username in the process.

**This PR comes with a big caveat**: I have NOT been able to verify the new option behaves as expected when in the DEFAULT section mentioned in the README. We probably should check that before merging.

### CODE REVIEW

**Comment by languitar** [comment]
Thanks for the PR. I suspect I should add some tests to this project before merging the PR to ensure that nothing else gets broken. This would then also provide the opportunity to check the default behavior.

**Comment by languitar** [comment]
> ... I have to `pass generate` every 30 days, overwriting the username in the process.

Btw, `pass generate -i` would replace the password without changing anything else in the file.

**Comment by DIzFer** [comment]
Ha, good to know. Thanks.

**Comment by languitar** [comment]
@DIzFer  I have put some implementation to solve your request in a more generic way into branch feature-username-selector. Could you have a look whether this solves all needs reflected in this PR?

**Pull request closed without merging**
